contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #downstream channel"
    url: https://nfcore.slack.com/channels/downstream
    about: Discussion about the nf-core/downstream pipeline
