name: docker-build-push
#https://github.com/marketplace/actions/build-and-push-docker-images

on:
  push:
    branches: 
      - main
    paths: 
      - '**/Dockerfile'

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        tag: ["base"]
        docker-file: ["Dockerfile"]
        module-name: ["schelper", "archr", "archr_r4.1.2"]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: evahamrud
          password: DockerPassword
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: NF-downstream_analysis/containers/${{matrix.module-name}}
          push: true
          tags: evahamrud/sc_multi_omic-${{matrix.module-name}}:latest
    
